version: '3'

services:
  node-app:
    container_name: toolbox-backend
    build:
      context: .
      dockerfile: /backend/Dockerfile
    ports:
      - '3030:3030'
    restart: always

  react-app:
    container_name: toolbox-frontend
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    ports:
      - '3031:3031'
    restart: always
